#!/bin/sh

if [ ! -f "./lsb_release.ori" ]
then # do a backup of lsb_release
    cp -p lsb_release lsb_release.ori
fi
mv -f lsb_release  lsb_release.tmp # lsb_release need to be parsed for
                                   # the help2man perl script
cat lsb_release.tmp | sed -e "s/\[ -n \"\$ARG_V\" \] \&\& DisplayVersion/\[ -n \"\$ARG_V\" \] \&\& Version/" >./lsb_release

chmod a+x ./lsb_release

rm -f lsb_release.1 lsb_release.1.bz2 # remove old man pages

# build man page
./help2man -N --include ./lsb_release.examples ./lsb_release >lsb_release.1

bzip2 lsb_release.1 # do the needed compression

# restore former lsb_release script
cat lsb_release | sed -e "s/\[ -n \"\$ARG_V\" \] \&\& Version/\[ -n \"\$ARG_V\" \] \&\& DisplayVersion/" >./lsb_release.tmp
mv -f lsb_release.tmp  lsb_release
chmod a+x ./lsb_release

cp lsb_release.1.bz2 /usr/man/man1/ # install place

man lsb_release # view the result
